In [1]:
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('news.csv',index_col=None)

In [3]:
df

Unnamed: 0                                              title  \
0           8476                       You Can Smell Hillary’s Fear   
1          10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2           3608        Kerry to go to Paris in gesture of sympathy   
3          10142  Bernie supporters on Twitter erupt in anger ag...   
4            875   The Battle of New York: Why This Primary Matters   
...          ...                                                ...   
6330        4490  State Department says it can't find emails fro...   
6331        8062  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...   
6332        8622  Anti-Trump Protesters Are Tools of the Oligarc...   
6333        4021  In Ethiopia, Obama seeks progress on peace, se...   
6334        4330  Jeb Bush Is Suddenly Attacking Trump. Here's W...   

                                                   text label  
0     Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1     Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2     U.S. Secretary of State John F. Kerry said Mon...  REAL  
3     — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4     It's primary day in New York and front-runners...  REAL  
...                                                 ...   ...  
6330  The State Department told the Republican Natio...  REAL  
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...  FAKE  
6332   Anti-Trump Protesters Are Tools of the Oligar...  FAKE  
6333  ADDIS ABABA, Ethiopia —President Obama convene...  REAL  
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...  REAL  

[6335 rows x 4 columns]

In [4]:
dataset=df.drop("Unnamed: 0",axis=1)

In [5]:
dataset

title  \
0                          You Can Smell Hillary’s Fear   
1     Watch The Exact Moment Paul Ryan Committed Pol...   
2           Kerry to go to Paris in gesture of sympathy   
3     Bernie supporters on Twitter erupt in anger ag...   
4      The Battle of New York: Why This Primary Matters   
...                                                 ...   
6330  State Department says it can't find emails fro...   
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...   
6332  Anti-Trump Protesters Are Tools of the Oligarc...   
6333  In Ethiopia, Obama seeks progress on peace, se...   
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...   

                                                   text label  
0     Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1     Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2     U.S. Secretary of State John F. Kerry said Mon...  REAL  
3     — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4     It's primary day in New York and front-runners...  REAL  
...                                                 ...   ...  
6330  The State Department told the Republican Natio...  REAL  
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...  FAKE  
6332   Anti-Trump Protesters Are Tools of the Oligar...  FAKE  
6333  ADDIS ABABA, Ethiopia —President Obama convene...  REAL  
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...  REAL  

[6335 rows x 3 columns]

In [6]:
y=dataset["label"]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(dataset['text'], y, test_size=0.33, random_state=53)

In [8]:
count_vectorizer = CountVectorizer(stop_words='english')
count_train = count_vectorizer.fit_transform(X_train)
print(count_train)
count_test = count_vectorizer.transform(X_test)

  (1, 42470)	1
  (1, 12105)	1
  (1, 54177)	1
  (1, 50628)	1
  (1, 15924)	2
  (1, 44520)	2
  (1, 51896)	2
  (1, 35783)	4
  (1, 35256)	1
  (1, 21881)	1
  (1, 42534)	1
  (1, 8399)	1
  (1, 29531)	2
  (1, 15927)	2
  (1, 25686)	1
  (1, 49203)	2
  (1, 16814)	1
  (1, 36087)	1
  (1, 21568)	1
  (1, 25684)	1
  (1, 38823)	1
  (1, 47506)	1
  (1, 36831)	1
  (2, 16972)	1
  (2, 762)	1
  :	:
  (4243, 41435)	1
  (4243, 53607)	1
  (4243, 659)	1
  (4243, 38834)	1
  (4243, 19003)	1
  (4243, 11415)	1
  (4243, 7545)	1
  (4243, 22426)	1
  (4243, 54007)	1
  (4243, 7113)	1
  (4243, 4932)	1
  (4243, 39497)	1
  (4243, 50053)	1
  (4243, 38849)	1
  (4243, 20702)	1
  (4243, 42139)	1
  (4243, 17247)	1
  (4243, 50052)	1
  (4243, 55228)	1
  (4243, 29255)	1
  (4243, 49435)	1
  (4243, 11257)	1
  (4243, 52945)	1
  (4243, 20905)	1
  (4243, 7962)	1


In [20]:
#dir(count_train)

In [9]:
len(count_vectorizer.get_feature_names_out())

56922

In [10]:
print(count_train.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:
from sklearn.naive_bayes import MultinomialNB
classifier_MNB = MultinomialNB()
classifier_MNB.fit(count_train, y_train)
y_pred = classifier_MNB.predict(count_test)
score = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.2f" % score)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
# Final prediction 
Final_pred = classifier_MNB.predict(count_train[0])
print(Final_pred)

accuracy:   0.89
              precision    recall  f1-score   support

        FAKE       0.92      0.86      0.89      1008
        REAL       0.88      0.93      0.90      1083

    accuracy                           0.89      2091
   macro avg       0.90      0.89      0.89      2091
weighted avg       0.89      0.89      0.89      2091

['FAKE']


In [12]:
from sklearn.naive_bayes import BernoulliNB
classifier_BNB = BernoulliNB()
classifier_BNB.fit(count_train, y_train)
y_pred = classifier_BNB.predict(count_test)
score = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.2f" % score)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
# Final prediction 
Final_pred = classifier_BNB.predict(count_train[0])
print(Final_pred)

accuracy:   0.82
              precision    recall  f1-score   support

        FAKE       0.77      0.92      0.83      1008
        REAL       0.90      0.74      0.81      1083

    accuracy                           0.82      2091
   macro avg       0.84      0.83      0.82      2091
weighted avg       0.84      0.82      0.82      2091

['FAKE']


In [13]:
from sklearn.naive_bayes import ComplementNB
classifier_CNB =ComplementNB()
classifier_CNB.fit(count_train, y_train)
y_pred = classifier_CNB.predict(count_test)
score = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.2f" % score)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
# Final prediction 
final_pred = classifier_CNB.predict(count_train[0])
print(final_pred)

accuracy:   0.89
              precision    recall  f1-score   support

        FAKE       0.92      0.86      0.89      1008
        REAL       0.88      0.93      0.90      1083

    accuracy                           0.89      2091
   macro avg       0.90      0.89      0.89      2091
weighted avg       0.89      0.89      0.89      2091

['FAKE']


In [14]:
# THIS IS NOT WORKING FOR CATEGORICAL NAIVE BAYES
from sklearn.naive_bayes import CategoricalNB
classifier = CategoricalNB()
classifier.fit(count_train, y_train)
y_pred = classifier.predict(count_test)
score = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.2f" % score)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)

TypeError: A sparse matrix was passed, but dense data is required. Use X.toarray() to convert to a dense numpy array.

In [15]:
from sklearn.neighbors import KNeighborsClassifier
classifier_KNC = KNeighborsClassifier(n_neighbors = 7, metric = 'minkowski', p = 2)
classifier_KNC.fit(count_train, y_train)
y_pred = classifier_KNC.predict(count_test)
score = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.2f" % score)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
# Final prediction 
final_pred = classifier_KNC.predict(count_train[0])
print(final_pred)

accuracy:   0.79
              precision    recall  f1-score   support

        FAKE       0.75      0.83      0.79      1008
        REAL       0.82      0.75      0.78      1083

    accuracy                           0.79      2091
   macro avg       0.79      0.79      0.79      2091
weighted avg       0.79      0.79      0.79      2091

['FAKE']


In [16]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.linear_model import LogisticRegression
classifier_LR =LogisticRegression(random_state=0)
classifier_LR.fit(count_train, y_train)
y_pred = classifier_LR.predict(count_test)
score = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.2f" % score)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
# Final prediction 
final_pred = classifier_LR.predict(count_train[0])
print(final_pred)

accuracy:   0.91
              precision    recall  f1-score   support

        FAKE       0.88      0.94      0.91      1008
        REAL       0.94      0.88      0.91      1083

    accuracy                           0.91      2091
   macro avg       0.91      0.91      0.91      2091
weighted avg       0.91      0.91      0.91      2091

['FAKE']


In [17]:
from sklearn.svm import SVC
classifier_SVC = SVC(kernel = 'rbf', random_state = 0)
classifier_SVC.fit(count_train, y_train)
y_pred = classifier_SVC.predict(count_test)
score = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.2f" % score)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
# Final prediction 
final_pred = classifier_SVC.predict(count_train[0])
print(final_pred)

accuracy:   0.86
              precision    recall  f1-score   support

        FAKE       0.79      0.96      0.87      1008
        REAL       0.96      0.77      0.85      1083

    accuracy                           0.86      2091
   macro avg       0.88      0.87      0.86      2091
weighted avg       0.88      0.86      0.86      2091

['FAKE']


In [18]:
from sklearn.svm import SVC
classifier_SVCL = SVC(kernel = 'linear', random_state = 0)
classifier_SVCL.fit(count_train, y_train)
y_pred = classifier_SVCL.predict(count_test)
score = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.2f" % score)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
# Final prediction 
final_pred = classifier_SVCL.predict(count_train[0])
print(final_pred)

accuracy:   0.87
              precision    recall  f1-score   support

        FAKE       0.86      0.88      0.87      1008
        REAL       0.89      0.86      0.87      1083

    accuracy                           0.87      2091
   macro avg       0.87      0.87      0.87      2091
weighted avg       0.87      0.87      0.87      2091

['FAKE']


In [19]:
from sklearn.tree import DecisionTreeClassifier
classifier_DT = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier_DT.fit(count_train, y_train)
y_pred = classifier_DT.predict(count_test)
score = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.2f" % score)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
# Final prediction 
final_pred = classifier_DT.predict(count_train[0])
print(final_pred)

accuracy:   0.82
              precision    recall  f1-score   support

        FAKE       0.81      0.82      0.81      1008
        REAL       0.83      0.82      0.82      1083

    accuracy                           0.82      2091
   macro avg       0.82      0.82      0.82      2091
weighted avg       0.82      0.82      0.82      2091

['FAKE']


In [20]:
from sklearn.ensemble import RandomForestClassifier
classifier_RF = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier_RF.fit(count_train, y_train)
y_pred = classifier_RF.predict(count_test)
score = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.2f" % score)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
# Final prediction 
final_pred = classifier_RF.predict(count_train[0])
print(final_pred)

accuracy:   0.84
              precision    recall  f1-score   support

        FAKE       0.80      0.90      0.85      1008
        REAL       0.90      0.78      0.84      1083

    accuracy                           0.84      2091
   macro avg       0.85      0.84      0.84      2091
weighted avg       0.85      0.84      0.84      2091

['FAKE']


In [27]:
from sklearn.linear_model import PassiveAggressiveClassifier
classifier_PAC = PassiveAggressiveClassifier(C = 0.5)
classifier_PAC.fit(count_train, y_train)
y_pred = classifier_PAC.predict(count_test)
score = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.2f" % score)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
# Final prediction 
final_pred = classifier_PAC.predict(count_train[0])
print(final_pred)

accuracy:   0.89
              precision    recall  f1-score   support

        FAKE       0.88      0.90      0.89      1008
        REAL       0.91      0.89      0.90      1083

    accuracy                           0.89      2091
   macro avg       0.89      0.89      0.89      2091
weighted avg       0.89      0.89      0.89      2091

['FAKE']


In [23]:
#clf = MultinomialNB()
#clf.fit(count_train, y_train)
#pred = clf.predict(count_test)
#score = metrics.accuracy_score(y_test, pred)
#print("accuracy:   %0.2f" % score)
#cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])
#from sklearn.metrics import classification_report
#report=classification_report(y_test, pred)
#print(report)

In [24]:
dataset["text"][0]

'Daniel Greenfield, a Shillman Journalism Fellow at the Freedom Center, is a New York writer focusing on radical Islam. \nIn the final stretch of the election, Hillary Rodham Clinton has gone to war with the FBI. \nThe word “unprecedented” has been thrown around so often this election that it ought to be retired. But it’s still unprecedented for the nominee of a major political party to go war with the FBI. \nBut that’s exactly what Hillary and her people have done. Coma patients just waking up now and watching an hour of CNN from their hospital beds would assume that FBI Director James Comey is Hillary’s opponent in this election. \nThe FBI is under attack by everyone from Obama to CNN. Hillary’s people have circulated a letter attacking Comey. There are currently more media hit pieces lambasting him than targeting Trump. It wouldn’t be too surprising if the Clintons or their allies were to start running attack ads against the FBI. \nThe FBI’s leadership is being warned that the entir

In [25]:
count_train[0]

<1x56922 sparse matrix of type '<class 'numpy.int64'>'
	with 0 stored elements in Compressed Sparse Row format>

In [26]:
count_vectorizer = CountVectorizer(stop_words='english')
count_train = count_vectorizer.fit_transform(X_train)
#print(count_train)
#count_test = count_vectorizer.transform(X_test)


In [27]:
#count_input=count_vectorizer.transform([[dataset["text"][0]]])
X_train[[0]]

0    Daniel Greenfield, a Shillman Journalism Fello...
Name: text, dtype: object

In [28]:
clf.predict(count_train[[0]])

array(['FAKE'], dtype='<U4')